# Generated by Django 6.0.5 on 2026-05-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'ordering': ['source_type']},
        ),
    ]
